name: CI Checks
on: [push]
jobs:
  model-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - run: doc
  build-core:
    runs-on: ubuntu-latest
    needs: model-check
    steps:
      - uses: actions/build@v2
      - run: cd
  build-and-test-otheres:
    runs-on: ubuntu-latest
    needs: [build-core, model-check]
    steps:
      - uses: actions/build@v2
      - uses: actions/test@v3
      - run: cd
  test-core:
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - uses: actions/test@v3
      - run: cd